### ISSUE TITLE
Problem with files with _task in file name

### ISSUE THREAD

**Issue by stegel** [dynamicdan/filesync#15]
Dan,

I created a new scss partial on my instance and when I try and create it locally and sync, I get an error. It appears like the code is adding an extra _ underscore to the filename

<img width="481" alt="screen shot 2015-12-19 at 4 28 38 pm" src="https://cloud.githubusercontent.com/assets/106086/11915293/bce0b99e-a66d-11e5-8ce1-103400bed29c.png">

**Comment by stegel** [comment]
So it doesn't seem to be just the filename "_task". I get it sporadically with different _ partials. Sometimes I just change the name on the instance until it works.

**Comment by dynamicdan** [comment]
This is potentially a known issue. I don't have an issue with other sass files but partials may need some more support. 

There was originally an issue when record names started with an _ or strange symbol. I am already in the process of switching to sys_id based communication so file naming issues will be less of an issue in the next major release.

**Comment by dynamicdan** [comment]
The original concept with SASS/SCSS support is that a separate theme is used so that no new tables need to be created. This theme is then not active but available to help future developers or the customer understand that SASS has been used. To separate CSS from SCSS files it was then required to postfix the SASS records with "_scss".

Therefore, the instance record name would be something like "_disclaimer_scss" which would be synced to a file called "_disclaimer.scss".

Your custom table should not be negatively affected. If you have issues try naming the records with "_scss" at the end.

The double underscore in the notification can safely be ignored. This is linked to the notification module and will go away with a future update.
